<?php

return [
    'crm' => [
        'clients' => [
            'groups' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'status' => 'Toggle Status',
            ],
        ],
    ],
    'supports' => [
        'tasks' => [
            'task_categories' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'status' => 'Toggle Status',
            ],
            'task_areas' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'status' => 'Toggle Status',
            ],
            'task_statuses' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'status' => 'Toggle Status',
            ],
            'tasks' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'status' => 'Toggle Status',
                'assign' => 'Assign',
            ],
        ],
    ],
    'networking' => [
        'general_settings' => [
            'packages' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'status' => 'Toggle Status',
                'sync' => 'Sync Mikrotik',
            ],
            'radius' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'status' => 'Toggle Status',
                'test-connection' => 'Test Connection',
            ],
            'mikrotiks' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'status' => 'Toggle Status',
                'details' => 'View Details',
                'overview' => 'View Overview',
                'mikrotik' => 'View Mikrotik',
                'update-mikrotik-api' => 'Update Mikrotik API',
                'check-mikrotik-status' => 'Check Mikrotik Status',
                'ping' => 'Ping',
                'radius-configuration' => 'Sync Radius Configuration',
                'test-connection' => 'Test Connection',
            ],
            'ipv4pools' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'status' => 'Toggle Status',
                'graph' => 'View Graph',
                'details' => 'View Details',
                'overview' => 'View Overview',
                'network' => 'View Network',
                'ping' => 'Ping',
            ],
            'ipv6pools' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'status' => 'Toggle Status',
                'graph' => 'View Graph',
                'details' => 'View Details',
                'overview' => 'View Overview',
                'network' => 'View Network',
                'ping' => 'Ping',
            ],
        ],
    ],
    'settings' => [
        'templates' => [
            'whatsapp' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
            ],
            'sms' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
            ],
            'email' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
            ],
        ],
        'configurations' => [
            'whatsapp' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'set_default' => 'Set Default',
                'send_test' => 'Send Test',
            ],
            'sms' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'set_default' => 'Set Default',
                'send_test' => 'Send Test',
            ],
            'email' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'set_default' => 'Set Default',
                'send_test' => 'Send Test',
            ],
        ],
        'roles_and_permissions' => [
            'roles' => [
                'index' => 'List',
                'create' => 'Create',
                'update' => 'Update',
                'delete' => 'Delete',
                'show' => 'Show',
                'assign' => 'Assign',
                'status' => 'Toggle Status',
            ],
            'permissions' => [
                'index' => 'List',
                'update' => 'Update',
            ],
        ],
    ],
];
